### ISSUE TITLE
CF2 SMARTS

### ISSUE THREAD

**Issue by adalke** [PatWalters/rd_filters#3]
In Notes.txt you write that you replaced $(CF2) with [CF2] to make it something that RDKit will parse.

The "[CF2]" means "atom with isotope number 2 and is carbon and fluorine", which is impossible to match.

I think the SMARTS of $(CF2) is trying to be $(C(F)F). The "CF2" is supposed to be a SMARTS expression, but in this case it has the unclosed ring closure "2". SMARTSViewer also complains about the $(CF2) saying "SMARTS Warning: Unpaired ring bonds!"

This suggests that the ChEMBL tool ignores the illegal SMARTS. I wonder if it matches CF (when there aren't 2 fluorines), or if it ignores that term (ie, not match CF at all), or ignores any matches.

I see nothing wrong with your other fixes.

**Comment by PatWalters** [comment]
Thanks, Andrew, I'll change that.

**Comment by pieterhbos** [comment]
To add to this, the alert_collection.csv contains 10 additional cases with "CF2".
One in rule 196 and nine in rule 245.
Replacing [CF2] with C(F)F fixes the issue

**Comment by PatWalters** [comment]
Sorry, thought I had fixed that one.  The rules have been updated.
