### ISSUE TITLE
SMARTS Parse error for rule 194

### ISSUE THREAD

**Issue by pieterhbos** [PatWalters/rd_filters#4]
The SMARTS pattern for rule 194 in the file alert_collection.csv gives a SMARTS parse error:

`[F,Cl,Br,I,$(O(S(=O)(=O)))]-[CH,CH2;!$(C(F)F]-[N,n]`

The pattern is missing a closing bracket. The fixed version looks like this:

`[F,Cl,Br,I,$(O(S(=O)(=O)))]-[CH,CH2;!$(C(F)F)]-[N,n]`

**Comment by PatWalters** [comment]
Fixed, thanks!
