### ISSUE TITLE
multiprocessing 

### ISSUE THREAD

**Issue by shhong0** [PatWalters/rd_filters#6]
Hi, 
I want use only 40 cpu cores. I use --np 40 option. 
However, rd_filter use all cpu cores.
I checked the rd_filters.py file.
rd_filters get "np" and assign to "num_cores". 
However, "num_cores" did not used after. Just repeated mp.cpu_count(). 

num_cores = cmd_input.get("--np") or mp.cpu_count()
num_cores = int(num_cores)
print("using %d cores" % num_cores, file=sys.stderr)
p = Pool(mp.cpu_count())

Thanks

**Comment by PatWalters** [comment]
fixed, sorry for the hassles
