### ISSUE TITLE
How are valence errors handled?

### ISSUE THREAD

**Issue by mlkelly14** [PatWalters/rd_filters#7]
Hi Pat,

Thank you for this excellent software! Quick question - I am using it for large libraries of molecules, which I standardize and clean before using rd_filters, but some of the larger elements with noncanonical valences (like 6 bonds to Silicon) are flagged with an error that is printed as it runs such as "Explicit valence for atom # 0 N, 4, is greater than permitted". When this happens, are those molecules with valence errors automatically filtered out, automatically passed over and kept in the output file, or are they processed by the script and filtered in or out based on the criteria regardless of the valence flag? Thank you very much!

**Comment by PatWalters** [comment]
The molecule is written to the output file and marked with the filter "INVALID" 

,SMILES,NAME,FILTER,MW,LogP,HBD,HBA,TPSA
0,N(C)(C)(C)C,test,INVALID,-999,-999,-999,-999,-999
