### ISSUE TITLE
BMS "contains_metal" filter hits aromatic sulfurs

### ISSUE THREAD

**Issue by MikeBowerReverie** [PatWalters/rd_filters#8]
because of $([as]).  this seems to be interpreted as an environment of any aromatic atom next to an aromatic sulfur.  Possibly use atomic number for arsenic?  

![image](https://user-images.githubusercontent.com/57106393/74251223-cb330280-4cb9-11ea-93ca-e15a790442e2.png)

**Comment by leelasd** [comment]
I think this could be resolved by going from `[as]` to `[As]` 
`[as]` could be finding hitting aromatic sulphur atoms.

**Comment by PatWalters** [comment]
Made a change to the smarts so that [Se],[se] is replaced by [#34] and [As],[as] is replaced by [#33]
